[general]
log_dir = "logs"
profile_dir = "data/profiles"
faiss_dir = "data/faiss_index"

[llm]
model_name = "openai/gpt-oss-20b"
temperature = 0.7

[embeddings]
semantic_model = "sentence-transformers/all-MiniLM-L6-v2"
emotion_classifier_model = "j-hartmann/emotion-english-distilroberta-base"

[chatbot]
recent_messages_k = 12
top_k_vector_search = 20
num_kb_chunks_in_context = 3
num_recent_user_messages_in_context = 2

[scoring_weights]
semantic = 0.55
emotion = 0.2
profile_match = 0.1
recency = 0.1
style_match = 0.05
