[general]
log_dir = "logs"
profile_dir = "data/profiles"
faiss_dir = "data/faiss_index"

[llm]
model_name = "llama3-8b-8192"
temperature = 0.7

[embeddings]
semantic_model = "sentence-transformers/all-MiniLM-L6-v2"
emotion_classifier_model = "j-hartmann/emotion-english-distilroberta-base"
